### ISSUE TITLE
Unable to complete WHIP handshake with Cloudflare Streams

### ISSUE THREAD

**Issue by birme** [Eyevinn/whip-mpegts#18]
Currently WHIP ingest to Cloudflare does not work with whip-mpegts and needs to be investigated.

1. Sign up for an account att Cloudflare
2. Go to Cloudflare Streams
3. Create a Live input
4. Choose the WebRTC (WHIP) Beta and the WHIP endpoint URL available

Run whip-mpegts with the URL in 4

**Comment by oshinongit** [comment]
The problem is that the whipclient tries to find a header by key "location". Cloudflare server's key instead has a capitalized first letter "Location" which causes the logic in whipClient.cpp to fail.
