### ISSUE TITLE
Possible to set local ip to use for local ICE candidate gathering

### ISSUE THREAD

**Issue by birme** [Eyevinn/whip-mpegts#3]
When running the application in a Docker container in `host` network mode we need to be able to specify which local IP address to use for local ICE candidate gathering. The reason is the container will have multiple interfaces and the auto discovery may choose the container IP and not the host IP. On Linux it can look like this within a container where eno1 is the host interface in this example:

```
docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.18.0.1  netmask 255.255.0.0  broadcast 172.18.255.255
        inet6 fe80::42:afff:fed5:7d4a  prefixlen 64  scopeid 0x20<link>
        ether 02:42:af:d5:7d:4a  txqueuelen 0  (Ethernet)
        RX packets 93338  bytes 6913369 (6.9 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 234890  bytes 1195609220 (1.1 GB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eno1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.17.28.156  netmask 255.255.255.0  broadcast 172.17.28.255
        inet6 fe80::3933:bd04:7a71:e401  prefixlen 64  scopeid 0x20<link>
        ether 1c:98:ec:52:c3:14  txqueuelen 1000  (Ethernet)
        RX packets 1067002987  bytes 400211764156 (400.2 GB)
        RX errors 0  dropped 397  overruns 0  frame 0
        TX packets 1901345711  bytes 2668405035544 (2.6 TB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 16  
```

The webrtcbin has a way to set the local IP and perhaps that can be used: https://gstreamer.freedesktop.org/documentation/webrtc/index.html?gi-language=c#GstWebRTCICE::add-local-ip-address

**Comment by marcusspangenberg** [comment]
The connectivity issues turned out to be related to an old version of gstreamer. I switched to debian:bullseye docker base image to get a functional newer gstreamer version.
